### ISSUE TITLE
Fix PEP8 violations in code style

### ISSUE THREAD

**Issue by akshgpt7** [akshgpt7/MarvellOS#10]
The current coding style does not conform to [PEP8](https://www.python.org/dev/peps/pep-0008/) standards.
Use a tool like `pycodestyle` or `flake8` (preferred) to find all the violations and fix them for more readable and standard coding style.

**Comment by osBins** [comment]
Hi, I would like to work on this issue.

**Comment by akshgpt7** [comment]
@osBins Go ahead! Ask away if you feel stuck.

**Comment by ArunS-tack** [comment]
Can I work on it?

**Comment by akshgpt7** [comment]
@ArunSanganal, sorry but I think @osBins is already working on this. Maybe you can look for another issue?

**Comment by abdulrahman-pydevQ8** [comment]
can i work in it pls

**Comment by akshgpt7** [comment]
Sorry, but this has already been fixed via #37.
I forgot to close the issue.
You can check out other issues if you'd like to work on any :)
