### ISSUE TITLE
Make every window non-resizable

### ISSUE THREAD

**Issue by akshgpt7** [akshgpt7/MarvellOS#12]
The positioning of all components is set keeping in mind that the window is not resized by the user. 
Make all the windows that open non-resizable, so that the user cannot change its size once they open.

**Comment by khushi0704** [comment]
Hey , I have solved this issue and have made a pull request , Kindly please accept it and mark the issue as kwoc .

**Comment by akshgpt7** [comment]
Fixed in #13.
