### ISSUE TITLE
Make a global string for window geometry

### ISSUE THREAD

**Issue by akshgpt7** [akshgpt7/MarvellOS#19]
The geometry for each window needs to be same, but it's manually entered for every window. It'll be easier if there's a global string that contains that geometry value, and is directly used in the `geometry()` method of every window.
This will make it easier if we later plan to change this value, since it'll only have to be changed at one place instead of doing that for every window individually.

**Comment by ConsultantFoodie** [comment]
I would like to work on this. Can you assign it to me?

**Comment by akshgpt7** [comment]
@ConsultantFoodie Go for it!
