### ISSUE TITLE
Add titles to all windows

### ISSUE THREAD

**Issue by akshgpt7** [akshgpt7/MarvellOS#23]
Currently, titles are only shown for the welcome screen and home screen. 
It'll be good to show the window title on all the windows.

**Comment by priyasingh456** [comment]
@akshgpt7 can I work on this issues.

**Comment by akshgpt7** [comment]
@priyasingh456 Go for it.

**Comment by deepdarshan21** [comment]
@akshgpt7 can i do it

**Comment by akshgpt7** [comment]
@priyasingh456 are you still working on this?
If she doesn't respond, @deepdarshan21 you can take this.

**Comment by deepdarshan21** [comment]
@akshgpt7 resolved the problem in pull request #33. Please review that
