### ISSUE TITLE
Use binary mode text file to store password

### ISSUE THREAD

**Issue by akshgpt7** [akshgpt7/MarvellOS#3]
Currently, the password is stored as plain text.
Using a binary mode to store will make it safer.

**Comment by sharonMandel** [comment]
Do you mean encrypt text to binary?

**Comment by akshgpt7** [comment]
Yes, open the password.txt file in write binary mode and then write it. Also, make sure it is checked correctly when user enters a password.

**Comment by sharonMandel** [comment]
If I understand correct:
1. open text file and read the content (which is password).
2. write the password in binary mode to the text file.
3. compare the password from the screen [not sure what you meant about this part] to the one which is saved in the file [in step 2]?
Is this correct?

**Comment by akshgpt7** [comment]
Yes, that is what is needed.
Basically, the current problem is that the password is visible in the text file. If it is stored in binary encrypted form, it'll not be that obvious to look at.
So, rather than opening the file in ```w``` mode, use ```wb``` mode when someone changes the password.
Similarly, ```rb``` mode for reading.

**Comment by MercerFrey** [comment]
Hello, I want to contribute. Is it fine to encode password to base64?

**Comment by akshgpt7** [comment]
Yes, that would do. Go ahead!

**Comment by akshgpt7** [comment]
Fixed by #8
